# Generated by Django 3.2.4 on 2024-07-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idUsuarios', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombresu', models.CharField(db_column='nombres', default='', max_length=100)),
                ('apellidosu', models.CharField(db_column='apellidos', default='', max_length=100)),
                ('usuariou', models.CharField(db_column='usuario', default='', max_length=100, unique=True)),
                ('contraseñau', models.CharField(db_column='contrasena', default='', max_length=100)),
                ('is_superUser', models.BooleanField(db_column='is_superUser', default=False)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
