# Generated by Django 3.2.4 on 2024-07-17 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventanilla', '0006_alter_ventanilla_nprog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('archivo_pdf', models.FileField(upload_to='media/')),
                ('nprog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventanilla.ventanilla')),
            ],
            options={
                'db_table': 'inspeccion',
            },
        ),
    ]
