# Generated by Django 3.2.4 on 2024-07-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspeccion',
            name='ID',
            field=models.CharField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
