# Generated by Django 4.2.10 on 2024-06-04 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(to='inspeccion.categoria'),
        ),
    ]
