# Generated by Django 3.2.4 on 2024-07-26 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventanilla', '0008_alter_ventanilla_folio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idvit', models.CharField(blank=True, max_length=20, unique=True)),
                ('nombre_propietario', models.CharField(max_length=255)),
                ('fecha_revision', models.DateField()),
                ('carpeta', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('folio_manifestacion', models.CharField(max_length=255)),
                ('dia_que_sale', models.DateField()),
                ('plano_manzanero', models.FileField(upload_to='vitacora/')),
                ('verificacion_linderos', models.CharField(max_length=255)),
                ('tipo_captura', models.CharField(max_length=255)),
                ('clave_catastral', models.CharField(max_length=255)),
                ('costo_traslado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacion', models.TextField()),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventanilla.ventanilla', to_field='folio')),
            ],
            options={
                'db_table': 'vitacora',
            },
        ),
    ]
