# Generated by Django 3.2.4 on 2024-07-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitacora', '0002_auto_20240725_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitacora',
            name='id',
        ),
        migrations.AlterField(
            model_name='vitacora',
            name='idvit',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
