# Generated by Django 3.2.4 on 2024-07-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitacora', '0003_auto_20240726_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitacora',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], default='pendiente', max_length=20),
        ),
    ]
