# Generated by Django 4.2.10 on 2024-05-27 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventanilla', '0002_pruducto_created_pruducto_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pruducto',
            new_name='Producto',
        ),
    ]
