# Generated by Django 3.2.4 on 2024-06-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventanilla', '0005_ventanilla_delete_ventana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanilla',
            name='nprog',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
