# Generated by Django 3.2.4 on 2024-07-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventanilla', '0006_alter_ventanilla_nprog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventanilla',
            old_name='ccvc',
            new_name='tramite',
        ),
        migrations.RemoveField(
            model_name='ventanilla',
            name='cert_clave',
        ),
        migrations.RemoveField(
            model_name='ventanilla',
            name='cert_plano_mz',
        ),
        migrations.RemoveField(
            model_name='ventanilla',
            name='const_ident_catastral',
        ),
        migrations.RemoveField(
            model_name='ventanilla',
            name='levantamiento_topo',
        ),
        migrations.RemoveField(
            model_name='ventanilla',
            name='verificacion_linderos',
        ),
    ]
