# Generated by Django 3.2.4 on 2024-07-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventanilla', '0007_auto_20240717_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanilla',
            name='folio',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
