# Generated by Django 3.2.4 on 2024-08-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventanilla', '0008_alter_ventanilla_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanilla',
            name='observaciones_atencion',
            field=models.CharField(max_length=125),
        ),
        migrations.AlterField(
            model_name='ventanilla',
            name='pago',
            field=models.CharField(max_length=125),
        ),
    ]
