# Generated by Django 3.2.4 on 2024-08-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventanilla', '0009_auto_20240807_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanilla',
            name='pago',
            field=models.CharField(max_length=25),
        ),
    ]
