# Generated by Django 4.2.10 on 2024-05-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direccions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='imagen',
            field=models.ImageField(upload_to='direccions'),
        ),
    ]
